# Generated by Django 6.0.3 on 2026-04-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
    ]
