# Generated by Django 6.0.3 on 2026-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_clear_default_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status_text',
            field=models.CharField(blank=True, db_default='', default='', max_length=30, verbose_name='Статус документа'),
        ),
    ]
