# Generated by Django 6.0.3 on 2026-05-07 19:12

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, default='', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('password', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('token_hash', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
