# Generated by Django 6.0.3 on 2026-05-07 20:03

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerrequest',
            name='token_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='username',
            field=models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
