# Generated by Django 6.0.3 on 2026-05-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_registerrequest_token_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='status',
            field=models.CharField(
                choices=[('wait', 'Ожидание'), ('expired', 'Просрочено'), ('complete', 'Завершено')],
                db_default='wait',
                default='wait',
            ),
        ),
    ]
