# Generated by Django 6.0.3 on 2026-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registerrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerrequest',
            name='token_hash',
        ),
        migrations.AddField(
            model_name='registerrequest',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
