# Generated by Django 6.0.3 on 2026-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_favoriteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteuser',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
